package UI;

import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Chris
 */


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {        
        initComponents();
        InitStyles();
    }
    
    private void InitStyles(){
        usernameTextField.putClientProperty("JComponent.roundRect", true);
        userPasswordField.putClientProperty("JComponent.roundRect", true); 
        UIManager.put("usernameTextField.innerFocusWidth", 5);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        userPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        backGroundLabel = new javax.swing.JLabel();
        esquinaIzquierd = new javax.swing.JLabel();
        esquinaDerecha = new javax.swing.JLabel();
        esquinaDerechaBefore = new javax.swing.JLabel();
        esquinaIzquierdBefore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1116, 655));
        setMinimumSize(new java.awt.Dimension(1116, 655));
        setName("Sistema de Ayuda a Profesores"); // NOI18N
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\imgSap (1).png")); // NOI18N
        jLabel2.setFocusable(false);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 310, 240));

        usernameTextField.setBackground(new java.awt.Color(255, 255, 255));
        usernameTextField.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(0, 0, 0));
        usernameTextField.setText("Usuario");
        usernameTextField.setToolTipText("");
        usernameTextField.setMargin(new java.awt.Insets(0, 20, 0, 20));
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 234, 41));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 234, -1));

        userPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        userPasswordField.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        userPasswordField.setText("jPasswordField1");
        userPasswordField.setMargin(new java.awt.Insets(0, 20, 0, 20));
        jPanel2.add(userPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 234, 41));

        jButton1.setBackground(new java.awt.Color(132, 84, 234));
        jButton1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 132, 41));

        backGroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\Group 1.png")); // NOI18N
        jPanel2.add(backGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 530));

        esquinaIzquierd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\Ellipse 1.png")); // NOI18N
        esquinaIzquierd.setText("jLabel3");
        jPanel2.add(esquinaIzquierd, new org.netbeans.lib.awtextra.AbsoluteConstraints(-330, -150, 600, 430));

        esquinaDerecha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\Ellipse 2.png")); // NOI18N
        jPanel2.add(esquinaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 520, 420));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 840, 530));

        esquinaDerechaBefore.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\Ellipse 2.png")); // NOI18N
        jPanel1.add(esquinaDerechaBefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 490, 480));

        esquinaIzquierdBefore.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\Ellipse 1.png")); // NOI18N
        esquinaIzquierdBefore.setText("jLabel3");
        jPanel1.add(esquinaIzquierdBefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -100, 630, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGroundLabel;
    private javax.swing.JLabel esquinaDerecha;
    private javax.swing.JLabel esquinaDerechaBefore;
    private javax.swing.JLabel esquinaIzquierd;
    private javax.swing.JLabel esquinaIzquierdBefore;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
    
}
