package UI;

import com.aspose.cells.Cell;
import com.aspose.cells.Workbook;
import com.aspose.cells.Worksheet;
import com.christopher.testexcel.Profesores;
import com.christopher.testexcel.ProfesoresList;
import com.christopher.testexcel.Session;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Chris
 */


public class Login extends javax.swing.JFrame {

    int xMouse, yMouse;
    Profesores profesor = new Profesores("","","","");
    private Object valorCeldaId_profesor;
    private Object valorCeldaProfesor_name;
    private Object valorCeldaProfesor_usuario;
    private Object valorCeldaProfesor_pass;
    private Object valorCelda_cabecera;
    private List<Profesores> profesoresList = new ArrayList<>();
    private String userLogin;
    
    /**
     * Creates new form Login
     * @throws java.lang.Exception
     */
    public Login() throws Exception {        
        initComponents();
        InitStyles();
        this.setLocationRelativeTo(this);
        SetImageLabel(backGroundLabel, "src/main/java/Assets/backGroundLabel.png");
        SetImageLabel(esquinaIzquierdBefore, "src/main/java/Assets/EllipseIzq.png");
        SetImageLabel(esquinaDerecha, "src/main/java/Assets/EllipseDer.png");
        SetImageLabel(closeLabel, "src/main/java/Assets/close.png");
        SetImageLabel(logoSap, "src/main/java/Assets/Logo.png");
        initProfesor();
        
    }
    
    private void initProfesor() throws Exception{
        
        
        
        // Cargar archivo de Excel
        Workbook wb = new Workbook("Profesores_base.xlsx");

        // Obtener la hoja uno del libro
        Worksheet worksheet = wb.getWorksheets().get(0); // Hoja uno tiene el índice 0
        
        System.out.println("Profesores");
        int valor1 = 1;
        int valor2 =  2;
        
        
        do{
            Cell celdaCabecera = worksheet.getCells().get("A" + valor1);
            valorCelda_cabecera = celdaCabecera.getStringValue();
            Cell celdaId_profesor = worksheet.getCells().get("A" + valor2);
            valorCeldaId_profesor = celdaId_profesor.getStringValue();
            if(!(valorCeldaId_profesor.equals(""))){
                
                Cell celdaProfesor = worksheet.getCells().get("B" + valor2);
                valorCeldaProfesor_name = celdaProfesor.getStringValue();
                Cell celdaUsuario = worksheet.getCells().get("C" + valor2);
                valorCeldaProfesor_usuario = celdaUsuario.getStringValue();
                Cell celdaContrasena = worksheet.getCells().get("D" + valor2);
                valorCeldaProfesor_pass = celdaContrasena.getStringValue();

//                System.out.println("ProfesorId: " + valorCeldaId_profesor);
//                System.out.println("-Profesor: " + valorCeldaProfesor_name);
//                System.out.println("-Usuario profesor: " + valorCeldaProfesor_usuario);
//                System.out.println("-Usuario contrasena: " + valorCeldaProfesor_pass);
                
                
                profesor = new Profesores((String) valorCeldaId_profesor, (String) valorCeldaProfesor_name, (String) valorCeldaProfesor_usuario, (String) valorCeldaProfesor_pass);
                profesoresList.add(profesor);
                
                
            }
            valor1 += 1;
            valor2 += 1;
        }while (!valorCelda_cabecera.equals(""));
        profesor.setProfesoresList(profesoresList);
    }
    
    private void SetImageLabel(JLabel labelName, String root){
         ImageIcon image = new ImageIcon(root);
         Icon icon  = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
         labelName.setIcon(icon);
         this.repaint();
    }
    
    private void InitStyles(){
        usernameTextField.putClientProperty("JComponent.roundRect", true);
        userPasswordField.putClientProperty("JComponent.roundRect", true); 
        UIManager.put("usernameTextField.innerFocusWidth", 5);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        loginPanel = new javax.swing.JPanel();
        mainContentPanel = new javax.swing.JPanel();
        logoSap = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        backGroundLabel = new javax.swing.JLabel();
        esquinaIzquierdBefore = new javax.swing.JLabel();
        esquinaDerecha = new javax.swing.JLabel();
        toolBarPanel = new javax.swing.JPanel();
        closeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1116, 655));
        setMinimumSize(new java.awt.Dimension(1116, 655));
        setName("Sistema de Ayuda a Profesores"); // NOI18N
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginPanel.setForeground(new java.awt.Color(255, 255, 255));
        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainContentPanel.setBackground(new java.awt.Color(240, 233, 255));
        mainContentPanel.setForeground(new Color(0,0,0,10));
        mainContentPanel.setPreferredSize(new java.awt.Dimension(500, 300));
        mainContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoSap.setFocusable(false);
        mainContentPanel.add(logoSap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 310, 240));

        usernameTextField.setBackground(new java.awt.Color(255, 255, 255));
        usernameTextField.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(153, 153, 153));
        usernameTextField.setText("Usuario");
        usernameTextField.setToolTipText("");
        usernameTextField.setMargin(new java.awt.Insets(0, 20, 0, 20));
        usernameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usernameTextFieldMousePressed(evt);
            }
        });
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        mainContentPanel.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 234, 41));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Contraseña");
        mainContentPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 210, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        mainContentPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 234, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Usuario");
        mainContentPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 210, -1));

        userPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        userPasswordField.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        userPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        userPasswordField.setText("contrasena");
        userPasswordField.setMargin(new java.awt.Insets(0, 20, 0, 20));
        userPasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userPasswordFieldMousePressed(evt);
            }
        });
        userPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordFieldActionPerformed(evt);
            }
        });
        mainContentPanel.add(userPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 234, 41));

        jButton1.setBackground(new java.awt.Color(132, 84, 234));
        jButton1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainContentPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 140, 60));

        backGroundLabel.setBackground(new Color(0,0,0));
        backGroundLabel.setForeground(new Color(0,0,0,10));
        backGroundLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\backGroundLabel.png")); // NOI18N
        mainContentPanel.add(backGroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 830, 530));

        esquinaIzquierdBefore.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\EllipseIzq.png")); // NOI18N
        mainContentPanel.add(esquinaIzquierdBefore, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, -100, 570, 420));

        esquinaDerecha.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\EllipseDer.png")); // NOI18N
        mainContentPanel.add(esquinaDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 410, 330));

        toolBarPanel.setBackground(new java.awt.Color(240, 233, 255));
        toolBarPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        toolBarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                toolBarPanelMouseDragged(evt);
            }
        });
        toolBarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toolBarPanelMousePressed(evt);
            }
        });
        toolBarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        closeLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chris\\Desktop\\Proyecto Ecturas de datos\\testExcel\\src\\main\\java\\Assets\\close.png")); // NOI18N
        closeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        toolBarPanel.add(closeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 50, 50));

        mainContentPanel.add(toolBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 60));

        loginPanel.add(mainContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 660));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String profe1 = "chrisoch" ;
        String profe1Pass = "profesor1" ;
        String profe2 = "fernandocast" ;
        String profe2Pass = "profesor2" ;
        boolean founded = false; 
        
            if(profe1.equals(usernameTextField.getText()) && profe1Pass.equals(String.valueOf(userPasswordField.getPassword()))){
                Session usuarioLogin = new Session();
                usuarioLogin.setUsuarioLogeado("Christopher Ochoa");
                
                HomeParalelos homeSAPchris = new HomeParalelos(usuarioLogin);
                homeSAPchris.setVisible(true);
                
                this.dispose();                                
                founded = true;
            }
            if(profe2.equals(usernameTextField.getText()) && profe2Pass.equals(String.valueOf(userPasswordField.getPassword()))){
                Session usuarioLogin = new Session();
                usuarioLogin.setUsuarioLogeado("Fernando Castro");
                
                HomeParalelos2 homeSAPfernando = new HomeParalelos2(usuarioLogin);
                homeSAPfernando.setVisible(true);
                
                this.dispose();                                
                founded = true;
            }
         
        if(!founded){
            javax.swing.JOptionPane.showMessageDialog(this, "Error al Logear. Usuario y contraseña incorrecto: " + usernameTextField.getText() + " - " + String.valueOf(userPasswordField.getPassword()) );
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void toolBarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolBarPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_toolBarPanelMousePressed

    private void toolBarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolBarPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_toolBarPanelMouseDragged

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void usernameTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTextFieldMousePressed
        if(usernameTextField.getText().equals("Usuario")){
            usernameTextField.setText("");
            usernameTextField.setForeground(Color.black);
        }
        if(String.valueOf(userPasswordField.getPassword()).isEmpty()){
            userPasswordField.setText("contraseña");
            userPasswordField.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_usernameTextFieldMousePressed

    private void userPasswordFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPasswordFieldMousePressed
        if(String.valueOf(userPasswordField.getPassword()).equals("contrasena")){
            userPasswordField.setText("");
            userPasswordField.setForeground(Color.black);
            
        }
        if(usernameTextField.getText().isEmpty()){
            usernameTextField.setText("Usuario");
            usernameTextField.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_userPasswordFieldMousePressed

    private void userPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGroundLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel esquinaDerecha;
    private javax.swing.JLabel esquinaIzquierdBefore;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoSap;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel toolBarPanel;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
    
}
